name: Build thesis
on: [push]
jobs:
  build-thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          extra_system_packages: py3-pip
          pre_compile: "pip install --user ./pygments_ugent"
          root_file: |
            thesis.tex
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=build -shell-escape"
      - name: Upload thesis.pdf
        run: |
          curl -F pdf=@build/thesis.pdf -F token=${{ secrets.UPLOAD_TOKEN }} ${{ secrets.UPLOAD_URL }}
